### PR TITLE
Fixed canvas centering and scaling

### PR DESCRIPTION
**Pull request by samuelnilsson**
Changed so that the game canvas is horizontlly centered and scales according to window size. Also removed unnecessary window.load.

### CODE REVIEW

**Comment by Rovanion** [comment]
I totally get the css change, but I'm curious as to why we don't have to wait for window.load?

**Comment by samuelnilsson** [comment]
I'm not really sure. I have just seen phaser examples where they don't use it and it works. They discuss it here: http://www.html5gamedevs.com/topic/7437-why-not-use-windowonload/. It seems like phaser.io handles it internally somehow.

**Comment by Rovanion** [comment]
As I read that forum post we should still wait for window.load since we are including our JS in the header:

> window.onload is only needed if you include your JavaScript at the top of the html page (i.e. in the <head> tag)

**Comment by samuelnilsson** [comment]
Hm, it is weird that it works anyway. I removed it since they don't use window onload in tutorials and examples and it seems to make no difference in our case.

**Comment by Rovanion** [comment]
Yeah, it works on my computer too so I'll go ahead and merge this. They must have some internal logic to check that the canvas actually exists before they try to bind to it or something along those lines.

Good job mate!

**Pull request merged**
